version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy/
    image: 661988/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: 661988/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: 661988/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: 661988/udagram-frontend:local