apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: docker.io/661988/udagram-api-feed:v2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: database-1.cofxqdcklpio.us-east-1.rds.amazonaws.com
            - name: POSTGRES_DB
              value: postgres
            - name: AWS_BUCKET
              value: mybucket939774296840
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_PROFILE
              value: microservice
            - name: JWT_SECRET
              value: testing
            - name: URL
              value: http://localhost:8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram
    service: backend-feed
  name: backend-feed
spec:
  ports:
    - port: 8080
  selector:
    service: backend-feed
