apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: docker.io/661988/udagram-reverseproxy:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "80"
      port: 80
  selector:
    service: reverseproxy
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: reverseproxy
#   name: reverseproxy
# spec:
#   ports:
#     - name: "8080"
#       port: 8080
#       targetPort: 8080
#   selector:
#     service: reverseproxy
